# here we assemble all the credentials we need
# we flatten them from dicts
# you can rewrite this how you see fit, to grab the credentials
# this is typically step one of the playbook

- name: Set naming facts - Credentials
  ansible.builtin.set_fact:
    aiqum_hostname: "{{ aiqum.host      | default('') }}"
    aiqum_username: "{{ aiqum.user      | default('') }}"
    aiqum_password: "{{ aiqum.password  | default('') }}"

    vcenter_username: "{{ vcenter.user     | default('')}}"
    vcenter_password: "{{ vcenter.password | default('')}}"
    vcenter_hostname: "{{ vcenter.host     | default('')}}"

    ontap_username: "{{ ontap.user     | default('')}}"
    ontap_password: "{{ ontap.password | default('')}}"
    