---
- name: "Day 0 Operations - Deploy Simulator"
  hosts: "localhost"
  become: false
  gather_facts: false
  collections:
    - community.general.terraform
  vars_files:
    - "vars/defaults.yml"

  roles:
    - { role: facts, qtask: credentials }  
    - { role: simulator, qtask: facts }
    - { role: simulator, qtask: plan }    
    - { role: simulator, qtask: create }
    - { role: simulator, qtask: init }    
    - { role: cluster, qtask: facts }       
    - { role: cluster, qtask: create }     
    - { role: aiqum, qtask: facts }        
    - { role: aiqum, qtask: register }         
