---
- name: "Day 0 Operations - Destroy Simulator"
  hosts: "localhost"
  become: false
  gather_facts: false
  collections:
    - community.general.terraform
  vars_files:
    - "vars/defaults.yml"

  roles:
    - { role: facts, qtask: credentials }  
    - { role: aiqum, qtask: facts }
    - { role: aiqum, qtask: unregister }    
    - { role: ontap_simulator, qtask: facts }
    - { role: ontap_simulator, qtask: destroy }
